import Head from "next/head"
import styles from "../styles/home.module.scss"
import {Box, Center, Heading, Flex, VStack} from "@chakra-ui/react"
import Image from "next/image"
import SelectDifficulty from "../components/selectDifficulty"
import SelectColor from "../components/selectColor"
import logoImage from "../public/logo.jpg"
import Button from "../components/button"
import {useRouter} from "next/router"
import {useDispatch, useSelector} from "react-redux"
import {resetBoard} from "../chessEngine/chess"

const difficulties = ["beginner", "intermediate", "advanced", "expert"]

export default function Home() {
  const router = useRouter()
  const {isPlaying} = useSelector((state) => state.game)
  const dispatch = useDispatch()

  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex justify="center">
        <Image
          className={styles.logo}
          width={170}
          height={45}
          src={logoImage}
          alt="logo"
        />
      </Flex>
      <Flex
        flexDirection="column"
        justifyContent="space-around"
        height="100%"
        mt="80px"
      >
        <Center>
          <Box>
            <SelectDifficulty difficulties={difficulties} />
            <SelectColor />
            <Center mt="40px" mb="40px">
              <VStack>
                {isPlaying && (
                  <Button
                    onClick={() => {
                      router.push("/play")
                    }}
                    width="200px"
                  >
                    Resume Game
                  </Button>
                )}
                <Button
                  onClick={() => {
                    dispatch({type: "reset-board"})
                    resetBoard()
                    router.push("/play")
                  }}
                  width="200px"
                >
                  New Game
                </Button>
                {/* <Button
                  onClick={() => {
                    dispatch({type: "reset-scores"})
                    dispatch({type: "reset-arrows"})
                  }}
                  width="200px"
                >
                  reset scores
                </Button> */}
              </VStack>
            </Center>
          </Box>
        </Center>
      </Flex>
    </Box>
  )
}
