import Head from "next/head"
import ChessBoard from "../components/chessBoard"
import styles from "../styles/play.module.scss"
import {Box} from "@chakra-ui/react"
import GameOverModal from "../components/gameOverModal"
import Settings from "../components/settings"
import PlayingView from "../components/playingView"
import {useWindowSize} from "../utils/useWindowSize"
import MobileView from "../components/mobileView"

export default function Home() {
  const {width, height} = useWindowSize()
  let showMobileView
  if ((width > height && width <= 850) || width <= 600) {
    showMobileView = true
  } else {
    showMobileView = false
  }

  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showMobileView ? <MobileView /> : <PlayingView />}
      <GameOverModal />
      {/* {showMobileView ? null : <Settings />} */}
      <Settings />
    </Box>
  )
}
